### ISSUE TITLE
Error when adding to existing project with webviews

### ISSUE THREAD

**Issue by kelvinharron** [haroldadmin/WhatTheStack#29]
Hey! Thank you for this library. I just got it up and running and we're excited to catch those rare but annoying to debug crashes when away from our machines. I implemented it (0.3.0) into our existing project and had to make two changes to our codebase:

* Add `Configuration.Provider` interface for WorkManager in the main application, as we provide Workmanager through Dagger `WorkManager.getInstance(applicationContext)`.
* Add the following block of code in the Application onCreate: 
```
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
    if (packageName != getProcessName()) WebView.setDataDirectorySuffix(getProcessName())
}
```

The second fix was a result of whatthestack throwing the following exception:
<details>
  <summary>Stacktrace</summary>

```
  
  2021-12-03 23:59:10.482 17446-17446/com.myapp.name.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.myapp.name.dev:what_the_stack_process, PID: 17446
    java.lang.RuntimeException: Unable to create application com.myapp.name.DebugApplication: java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6465)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377
        at org.chromium.android_webview.AwBrowserProcess.a(PG:40)
        at kv.c(PG:90)
        at kv.b(PG:160)
        at kv.e(PG:177)
        at com.android.webview.chromium.WebViewChromiumFactoryProvider.getStatics(PG:204)
        at android.webkit.WebView.setWebContentsDebuggingEnabled(WebView.java:1974)
        at com.myapp.name.DebugApplication.onCreate(DebugApplication.kt:17)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1182)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```
</details>

I don't see any webview code in this repo, so I assume it's down to us having multiple webviews (and could be fixed by removing `WebView.setWebContentsDebuggingEnabled`). Happy to close this issue out as it could help others with the same issue.

**Comment by haroldadmin** [comment]
Thank you for highlighting the solution to your problem. I'll close the issue, but it'll be here for people who face a similar problem in the future.
