### ISSUE TITLE
Crash when using newer systemuicontroller dependency

### ISSUE THREAD

**Issue by fvito** [haroldadmin/WhatTheStack#33]
Hello

If target app is using newer version of `systemuicontroller` from accompanist (anything newer than 0.24.0), then Whats The Stack screen crashes with the following stack trace 
```
Process: com.haroldadmin.crashyapp:what_the_stack_process, PID: 9954
java.lang.NoSuchMethodError: No static method rememberSystemUiController(Landroidx/compose/runtime/Composer;I)Lcom/google/accompanist/systemuicontroller/SystemUiController; in class Lcom/google/accompanist/systemuicontroller/SystemUiControllerKt; or its super classes (declaration of 'com.google.accompanist.systemuicontroller.SystemUiControllerKt' appears in /data/app/~~_4awURteYBFPZaFNkqrgiA==/com.haroldadmin.crashyapp-qVRDMtt8OFur9dGDn3-XHQ==/base.apk)
       at com.haroldadmin.whatthestack.WhatTheStackActivity$onCreate$1.invoke(WhatTheStackActivity.kt:28)
       at com.haroldadmin.whatthestack.WhatTheStackActivity$onCreate$1.invoke(WhatTheStackActivity.kt:27)
```
                                                                                                    	
It looks like in version 0.25.0 the `rememberSystemUiController` function signature changed as seen [here](https://github.com/google/accompanist/blob/v0.25.0/systemuicontroller/src/main/java/com/google/accompanist/systemuicontroller/SystemUiController.kt#L184). It now takes an additional param of a `Window`, which I think breaks binary compatibility (even though a default is used in the `accompanist` library)

I think a simple version bump of the dependencies of this library should be enough to fix this issue. I can open a PR if necessary

**Comment by haroldadmin** [comment]
Happy to accept a PR for it! Thank you for investigating the issue.

**Comment by fvito** [comment]
Thank you, I've opened a PR
